[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_staking_program = "FDxReJFEFS2kWBW2vRZ6kkGAi3CueyqKBzSQceN6Jyy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
